### PR TITLE
Guarantee at least 1 layer of cells from PolygonInitializer

### LINKED ISSUE #736: PolygonInitializer does not work in 2D
The PolygonInitializer does not work in **2D** unless you specify an &lt;extrude **zMax="5"** zMin="0"/&gt; with a zMax at least as big as the cell &lt;width&gt; value.

In a 2D model, with &lt;extrude **zMax="1"** zMin="0"/&gt; and &lt;Width&gt;1&lt;/Width&gt; you get
image

In the same model with &lt;Width&gt;2&lt;/Width&gt;you get
image

If you increase the PolygonInitializer's &lt;extrude&gt; value (even though the model is 2D) to be at least as big as the cell &lt;width&gt; then it seems to work correctly.

&lt;Extrude zMax="5" zMin="0"/&gt;
          &lt;Width>5</Width&gt;

The Potts block
   &lt;Potts&gt;
      &lt;Dimensions x="100" y="100" z="1"/&gt;
      &lt;Steps>10001&lt;/Steps&gt;
      &lt;Temperature&gt;10.0&lt;/Temperature&gt;
      &lt;NeighborOrder&gt;3&lt;/NeighborOrder&gt;
   &lt;/Potts>

### PR DESCRIPTION
**Pull request by fyffep**
Fixes #736 -- See the issue for files to test with.
image
image

If the simulation is 2D (z dimension is 1), the Extrude XML parameter is now ignored.

### CODE REVIEW

File: CompuCell3D/core/CompuCell3D/steppables/PolygonFieldInitializer/PolygonFieldInitializer.cpp [hunk 1]
```diff
@@ -92,20 +92,28 @@ void PolygonFieldInitializer::init(Simulator *simulator, CC3DXMLElement *_xmlDat
...
 
-            if (regionVec[i]->findElement("Extrude")) {
+            if (regionVec[i]->findElement("Extrude") && dim.z > 1) {
                 CC3DXMLElement * extrudeXML = regionVec[i]->getFirstElement("Extrude");
                 initData.zMin = extrudeXML->getAttributeAsUInt("zMin");
                 initData.zMax = extrudeXML->getAttributeAsUInt("zMax");
+
+                //Try to help user render 1 layer of cells if they set Extrude incorrectly.
+                if (initData.zMax <= initData.zMin) {
+                    cout << "Warning: PolygonInitializer requires that zMax > zMin in the Extrude parameter.\n";
```
Comment (tjsego) [inline CompuCell3D/core/CompuCell3D/steppables/PolygonFieldInitializer/PolygonFieldInitializer.cpp:102]: Recommend using CC3DLogger here and throughout.

**Review by tjsego — COMMENTED** [review]
One comment. Otherwise this looks good to me.
